# Generated by Django 5.2.8 on 2025-11-25 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(help_text='One per line')),
                ('steps', models.TextField(help_text='One step per line')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('category', models.CharField(choices=[('mains', 'Mains'), ('desserts', 'Desserts'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('snacks', 'Snacks'), ('drinks', 'Drinks')], max_length=20)),
                ('cook_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
